# Generated by Django 2.2.6 on 2020-03-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='long',
            new_name='lng',
        ),
    ]
