# Generated by Django 2.2.6 on 2020-04-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200328_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='Events',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='ethos',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_time',
            new_name='start',
        ),
    ]
