# Generated by Django 2.2.6 on 2020-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DubBikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('bike_stands', models.CharField(max_length=200)),
                ('available_bike_stands', models.CharField(max_length=200)),
                ('available_bikes', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('last_update', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DubBusTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=200)),
                ('display_stop_id', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('last_updated', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PollData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('parameters', models.TextField()),
                ('counts_by_measurement', models.TextField()),
            ],
        ),
    ]
