# Generated by Django 2.2.6 on 2020-02-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DubBikes',
        ),
        migrations.DeleteModel(
            name='DubBusTime',
        ),
        migrations.DeleteModel(
            name='PollData',
        ),
    ]
