# Generated by Django 2.2.6 on 2020-02-06 15:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polldata',
            name='counts_by_measurement',
        ),
        migrations.RemoveField(
            model_name='polldata',
            name='parameters',
        ),
        migrations.AddField(
            model_name='polldata',
            name='measurements',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
