# Generated by Django 2.2.6 on 2019-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dub_bus_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopid', models.CharField(max_length=200)),
                ('displaystopid', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('lastupdated', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
