# Generated by Django 2.2.6 on 2020-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_auto_20200206_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikesAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('location_name', models.CharField(max_length=256)),
                ('number_of_bikes', models.IntegerField()),
                ('number_of_stands', models.IntegerField()),
                ('total_capacity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollutionAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('location_name', models.CharField(max_length=256)),
                ('parameter', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
