# Generated by Django 2.2.6 on 2019-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191125_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dub_bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('bike_stands', models.CharField(max_length=200)),
                ('available_bike_stands', models.CharField(max_length=200)),
                ('available_bikes', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('last_update', models.CharField(max_length=200)),
            ],
        ),
    ]
