# Generated by Django 2.2.6 on 2019-11-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dub_bikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dub_bus_time',
            name='lastupdated',
            field=models.CharField(max_length=200),
        ),
    ]
