# Generated by Django 2.2.6 on 2020-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bikesapidata_pollutionapidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesapidata',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bikesapidata',
            name='location_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bikesapidata',
            name='number_of_bikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bikesapidata',
            name='number_of_stands',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bikesapidata',
            name='total_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bikesapidata',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pollutionapidata',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pollutionapidata',
            name='location_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pollutionapidata',
            name='parameter',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pollutionapidata',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pollutionapidata',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=16, null=True),
        ),
    ]
