# Generated by Django 2.2.6 on 2020-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191129_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('parameters', models.TextField()),
                ('countsByMeasurement', models.TextField()),
            ],
        ),
    ]
