# Generated by Django 2.2.6 on 2020-02-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile'),
        ('dashboard', '0004_auto_20200213_1752'),
    ]

    operations = [
    ]
