# Generated by Django 2.2.6 on 2020-01-28 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_poll_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
