# Generated by Django 2.2.6 on 2020-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_merge_20200219_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField(null=True)),
                ('display_stop_id', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('shortname', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
