# Generated by Django 2.2.6 on 2020-02-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_busapidata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busapidata',
            name='display_stop_id',
        ),
        migrations.RemoveField(
            model_name='busapidata',
            name='last_updated',
        ),
    ]
