# Generated by Django 2.2.6 on 2020-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200220_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busapidata',
            name='stop_id',
        ),
        migrations.AddField(
            model_name='busapidata',
            name='stopid',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busapidata',
            name='latitude',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busapidata',
            name='longitude',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='busapidata',
            name='shortname',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
