# Generated by Django 2.2.6 on 2020-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200220_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAPIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('url_to_image', models.TextField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('sentiment', models.CharField(max_length=256, null=True)),
                ('sentiment_value', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
