# Generated by Django 2.2.6 on 2020-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_newsapidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=16)),
                ('pollution', models.DecimalField(decimal_places=8, max_digits=16)),
            ],
        ),
    ]
