# Generated by Django 2.2.6 on 2020-04-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200421_1117'),
        ('dashboard', '0012_auto_20200422_1534'),
    ]

    operations = [
    ]
